# Travis CI configuration file.

language: php

php:
    - 5.6
    - 7.0

before_script:
    # Install Composer dependencies
    - composer install -d plib/library

script:
    - php plib/library/vendor/bin/codecept run unit