<?php echo $this->renderTabs($this->tabs); ?>

<?php if (! \Modules_SpamexpertsExtension_Form_Settings::retrieveFromPleskLicense()) { ?>
<h4>You can buy antispam services and obtain valid configuration directives in our
    <a href="<?php

    echo method_exists('pm_Context', 'getBuyUrl')
        ? \pm_Context::getBuyUrl()
        : 'https://go.plesk.com/buy-plesk-ext/spamexperts-extension';

    ?>" target="_blank">online store</a></h4>
<?php } elseif ($this->configFromLicenseAvailable) { ?>
    <?php if ($this->configFromLicenseUsed) { ?>
        <h4>Configuration options from an Additional Plesk license are in use. Please click
            <a href="<?php

            echo $this->url(['controller' => 'index', 'action' => 'disablelicenseconfiguration']);

            ?>">here</a> to change to manual configuration.</h4>
    <?php } else { ?>
        <h4>Configuration options from an Additional Plesk license are available but not in use. Please click
            <a href="<?php

            echo $this->url(['controller' => 'index', 'action' => 'enablelicenseconfiguration']);

            ?>">here</a> to update configuration to the options from the license.</h4>
    <?php } ?>
<?php } ?>

<?php echo $this->form; ?>
