<?php echo $this->renderTabs($this->tabs); ?>

<h3>Information</h3>

<table border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="width:150px;"><strong>Plesk:</strong></td>
        <td>v<?php echo pm_ProductInfo::getVersion() . " (" . pm_ProductInfo::getPlatform() . ")"; ?></td>
    </tr>
    <tr>
        <td><strong>PHP version:</strong></td>
        <td><?php echo PHP_VERSION; ?></td>
    </tr>
    <tr>
        <td><strong>Extension version:</strong></td>
        <td><?php $ext = pm_Context::getModuleInfo();
            /** @noinspection PhpUndefinedFieldInspection */
            echo "v{$ext->version}-{$ext->release}"; ?></td>
    </tr>
</table><br>

<h3>Diagnostics</h3>

<table border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="width:150px;"><strong>Hashes:</strong></td>
        <td>...</td>
    </tr>
    <tr>
        <td><strong>SpamFilter API:</strong></td>
        <td>rev.<?php echo Modules_SpamexpertsExtension_SpamFilter_Api::getRevision(); ?></td>
    </tr>
    <tr>
        <td><strong>Plesk API:</strong></td>
        <td>v.<?php echo Modules_SpamexpertsExtension_Plesk_ApiClient::getVersion(); ?></td>
    </tr>
</table>
