<div>
    <h2>End User License Agreement</h2>
    <p>
        The End User License Agreement (EULA) is available for review 
        <a href="<?= $this->escape($this->eulaUrl) ?>" target="_blank">here.</a>
    </p>

    <h2>Privacy Policy</h2>
    <p>
        The Privacy Policy is available for review 
        <a href="<?= $this->escape($this->privacyUrl) ?>" target="_blank">here.</a>
    </p>

    <?= $this->form ?>
</div>
